import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Bungee } from "next/font/google";
import "./globals.css";
import Navbar from "../componentes/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // pesos disponibles: 100, 300, 400, 500, 700, 900
  variable: "--font-roboto", // variable CSS para usar en Tailwind
});

const bungee = Bungee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bungee",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Navbar></Navbar> */}
      <body className={` ${bungee.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
